// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Final_APIs.Data;

#nullable disable

namespace TP_Final_APIs.Migrations
{
    [DbContext(typeof(TpFinalContexts))]
    partial class TpFinalContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TP_Final_APIs.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entradas",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Principales",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bebidas",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Discount")
                        .HasColumnType("REAL");

                    b.Property<bool>("Favourite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HappyHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rabas con limón",
                            Discount = 0.0,
                            Favourite = true,
                            HappyHour = false,
                            IdCategory = 1,
                            Name = "Rabas",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Milanesa con jamón y queso",
                            Discount = 10.0,
                            Favourite = true,
                            HappyHour = false,
                            IdCategory = 2,
                            Name = "Milanesa Napolitana",
                            Price = 3500.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Coca Cola 500ml",
                            Discount = 0.0,
                            Favourite = false,
                            HappyHour = true,
                            IdCategory = 3,
                            Name = "Coca Cola",
                            Price = 800.0
                        });
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mail = "luis@gmail.com",
                            Name = "Luis",
                            Password = "lamismadesiempre",
                            Phone = "34112345",
                            Status = true
                        });
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.Category", b =>
                {
                    b.HasOne("TP_Final_APIs.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.Product", b =>
                {
                    b.HasOne("TP_Final_APIs.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TP_Final_APIs.Entities.User", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
